name: phys150-env
channels:
  - conda-forge
dependencies:
#  - jupyter
  - rise
  - numpy
  - matplotlib
  - ffmpeg
  - pip:
	- jupyter-contrib-nbextensions
  	- jupyter-nbextensions_configurator
 
	
